import type { SlotComida } from "@/types";

export const SLOTS_COMIDA: SlotComida[] = [
  {
    id: "desayuno",
    hora: "8:00 am",
    nombre: "Desayuno",
    opciones: [
      {
        id: "des-1",
        nombre: "Carnívoro clásico",
        tags: ["testosterona", "alta proteína"],
        calorias: 820,
        proteina: 58,
        carbohidratos: 42,
        grasas: 44,
        ingredientes: [
          { nombre: "Bistec de res (150g)", cantidad: "150g", proteina: 35, carbohidratos: 0, grasas: 18 },
          { nombre: "3 huevos fritos en mantequilla", cantidad: "3 piezas", proteina: 18, carbohidratos: 0, grasas: 15 },
          { nombre: "3 tortillas de maíz", cantidad: "3 piezas", proteina: 5, carbohidratos: 42, grasas: 3 },
          { nombre: "½ aguacate", cantidad: "½ pieza", proteina: 1, carbohidratos: 6, grasas: 11 },
        ],
      },
      {
        id: "des-2",
        nombre: "Sardina matutina",
        tags: ["omega-3", "acné", "B12"],
        calorias: 650,
        proteina: 54,
        carbohidratos: 32,
        grasas: 23,
        ingredientes: [
          { nombre: "Sardinas en agua (2 latas)", cantidad: "170g", proteina: 36, carbohidratos: 0, grasas: 8 },
          { nombre: "3 huevos revueltos en mantequilla", cantidad: "3 piezas", proteina: 18, carbohidratos: 0, grasas: 15 },
          { nombre: "1 naranja", cantidad: "1 pieza", proteina: 1, carbohidratos: 15, grasas: 0 },
          { nombre: "Raw honey (1 cda)", cantidad: "1 cda", proteina: 0, carbohidratos: 17, grasas: 0 },
        ],
        nota: "Cubre B12, vitamina D y omega-3. Alternativa al hígado para los mismos beneficios.",
      },
      {
        id: "des-3",
        nombre: "Batido volumen",
        tags: ["rápido", "2 min", "leche de coco"],
        calorias: 960,
        proteina: 37,
        carbohidratos: 132,
        grasas: 63,
        ingredientes: [
          { nombre: "3 huevos crudos", cantidad: "3 piezas", proteina: 18, carbohidratos: 0, grasas: 15 },
          { nombre: "2 plátanos maduros", cantidad: "2 piezas", proteina: 2, carbohidratos: 54, grasas: 0 },
          { nombre: "Crema de cacahuate (2 cdas)", cantidad: "2 cdas", proteina: 8, carbohidratos: 6, grasas: 16 },
          { nombre: "Raw honey (1.5 cdas)", cantidad: "1.5 cdas", proteina: 0, carbohidratos: 26, grasas: 0 },
          { nombre: "Leche de coco de lata (300ml)", cantidad: "300ml", proteina: 2, carbohidratos: 6, grasas: 27 },
          { nombre: "Avena cruda (70g)", cantidad: "70g", proteina: 9, carbohidratos: 46, grasas: 5 },
        ],
        nota: "Licúa todo. Ideal cuando no hay tiempo de cocinar. Usa leche de coco de LATA, no del cartón.",
      },
      {
        id: "des-4",
        nombre: "Picadillo + huevos",
        tags: ["testosterona", "zinc", "familiar"],
        calorias: 820,
        proteina: 55,
        carbohidratos: 59,
        grasas: 33,
        ingredientes: [
          { nombre: "Picadillo de res (180g)", cantidad: "180g", proteina: 32, carbohidratos: 12, grasas: 18 },
          { nombre: "3 huevos revueltos en mantequilla", cantidad: "3 piezas", proteina: 18, carbohidratos: 0, grasas: 15 },
          { nombre: "3 tortillas de maíz", cantidad: "3 piezas", proteina: 5, carbohidratos: 42, grasas: 3 },
          { nombre: "Raw honey (1 cda)", cantidad: "1 cda", proteina: 0, carbohidratos: 17, grasas: 0 },
        ],
      },
      {
        id: "des-5",
        nombre: "Machaca con huevo al rancho",
        tags: ["testosterona", "zinc", "tradicional"],
        calorias: 680,
        proteina: 45,
        carbohidratos: 44,
        grasas: 28,
        ingredientes: [
          { nombre: "Machaca (80g)", cantidad: "80g", proteina: 25, carbohidratos: 0, grasas: 8 },
          { nombre: "3 huevos en mantequilla", cantidad: "3 piezas", proteina: 18, carbohidratos: 0, grasas: 15 },
          { nombre: "3 tortillas de maíz", cantidad: "3 piezas", proteina: 5, carbohidratos: 42, grasas: 3 },
          { nombre: "1 naranja", cantidad: "1 pieza", proteina: 1, carbohidratos: 15, grasas: 0 },
        ],
      },
    ],
  },
  {
    id: "mediaManana",
    hora: "11:00 am",
    nombre: "Media mañana",
    opciones: [
      {
        id: "mm-1",
        nombre: "Batido clásico (tu receta)",
        tags: ["raw", "rápido", "2 min"],
        calorias: 640,
        proteina: 24,
        carbohidratos: 82,
        grasas: 43,
        ingredientes: [
          { nombre: "2 huevos crudos", cantidad: "2 piezas", proteina: 12, carbohidratos: 0, grasas: 10 },
          { nombre: "1 plátano maduro", cantidad: "1 pieza", proteina: 1, carbohidratos: 27, grasas: 0 },
          { nombre: "Crema de cacahuate (1 cda)", cantidad: "1 cda", proteina: 4, carbohidratos: 3, grasas: 8 },
          { nombre: "Raw honey (1 cda)", cantidad: "1 cda", proteina: 0, carbohidratos: 17, grasas: 0 },
          { nombre: "Leche de coco de lata (250ml)", cantidad: "250ml", proteina: 2, carbohidratos: 5, grasas: 22 },
          { nombre: "Avena cruda (50g)", cantidad: "50g", proteina: 6, carbohidratos: 33, grasas: 3 },
        ],
        nota: "Tu receta base. Funciona como desayuno, colación o post-entreno de emergencia.",
      },
      {
        id: "mm-2",
        nombre: "Sardina power",
        tags: ["omega-3", "acné", "anti-inflamatorio"],
        calorias: 400,
        proteina: 37,
        carbohidratos: 20,
        grasas: 22,
        ingredientes: [
          { nombre: "Sardinas en agua (2 latas)", cantidad: "170g", proteina: 30, carbohidratos: 0, grasas: 8 },
          { nombre: "1 manzana", cantidad: "1 pieza", proteina: 0, carbohidratos: 20, grasas: 0 },
          { nombre: "Cacahuates naturales (30g)", cantidad: "30g", proteina: 7, carbohidratos: 5, grasas: 14 },
        ],
        nota: "Los omega-3 de la sardina son directamente anti-inflamatorios para la piel. 2-3 veces por semana.",
      },
      {
        id: "mm-3",
        nombre: "Huevos + fruta + nueces",
        tags: ["simple", "sin cocinar"],
        calorias: 380,
        proteina: 20,
        carbohidratos: 38,
        grasas: 24,
        ingredientes: [
          { nombre: "2 huevos duros", cantidad: "2 piezas", proteina: 12, carbohidratos: 0, grasas: 10 },
          { nombre: "Almendras naturales (40g)", cantidad: "40g", proteina: 8, carbohidratos: 6, grasas: 14 },
          { nombre: "1 naranja", cantidad: "1 pieza", proteina: 0, carbohidratos: 15, grasas: 0 },
          { nombre: "Raw honey (1 cda)", cantidad: "1 cda", proteina: 0, carbohidratos: 17, grasas: 0 },
        ],
      },
      {
        id: "mm-4",
        nombre: "Cecina portátil",
        tags: ["testosterona", "para llevar", "sin cocinar"],
        calorias: 420,
        proteina: 26,
        carbohidratos: 31,
        grasas: 19,
        ingredientes: [
          { nombre: "Cecina (80g)", cantidad: "80g", proteina: 25, carbohidratos: 0, grasas: 8 },
          { nombre: "½ aguacate", cantidad: "½ pieza", proteina: 1, carbohidratos: 6, grasas: 11 },
          { nombre: "Fruta de temporada (mango, naranja)", cantidad: "1 pieza", proteina: 0, carbohidratos: 25, grasas: 0 },
        ],
        nota: "Fácil de llevar a donde sea. Cecina = proteína animal concentrada, sin procesar.",
      },
    ],
  },
  {
    id: "comida",
    hora: "2:00 pm",
    nombre: "Comida · Pre-entreno",
    opciones: [
      {
        id: "com-1",
        nombre: "Si hace pollo — doble porción",
        tags: ["familiar", "pre-entreno"],
        calorias: 800,
        proteina: 65,
        carbohidratos: 95,
        grasas: 10,
        ingredientes: [
          { nombre: "Pollo (pechuga o pierna, doble porción)", cantidad: "250g", proteina: 55, carbohidratos: 0, grasas: 8 },
          { nombre: "Arroz blanco (porción generosa)", cantidad: "200g cocido", proteina: 4, carbohidratos: 58, grasas: 0 },
          { nombre: "3 tortillas de maíz", cantidad: "3 piezas", proteina: 5, carbohidratos: 42, grasas: 3 },
          { nombre: "Toda la verdura o ensalada disponible", cantidad: "al gusto", proteina: 2, carbohidratos: 8, grasas: 0 },
        ],
        nota: "El único ajuste: pedir más de la proteína principal. Come todo el arroz y todas las verduras.",
      },
      {
        id: "com-2",
        nombre: "Si hace res o guisado",
        tags: ["testosterona", "familiar"],
        calorias: 820,
        proteina: 60,
        carbohidratos: 95,
        grasas: 20,
        ingredientes: [
          { nombre: "Toda la carne del guisado", cantidad: "~200g", proteina: 45, carbohidratos: 5, grasas: 18 },
          { nombre: "Arroz + frijoles (si hay)", cantidad: "porción normal", proteina: 10, carbohidratos: 65, grasas: 1 },
          { nombre: "3 tortillas de maíz", cantidad: "3 piezas", proteina: 5, carbohidratos: 42, grasas: 3 },
        ],
        nota: "Si hay frijoles, cómetelos. Raw honey de postre si quieres más calorías.",
      },
      {
        id: "com-3",
        nombre: "Si hace caldo",
        tags: ["colágeno", "familiar"],
        calorias: 700,
        proteina: 55,
        carbohidratos: 65,
        grasas: 15,
        ingredientes: [
          { nombre: "Toda la carne del caldo", cantidad: "~180g", proteina: 40, carbohidratos: 0, grasas: 12 },
          { nombre: "El caldo completo", cantidad: "1-2 tazas", proteina: 5, carbohidratos: 0, grasas: 3 },
          { nombre: "Arroz + tortillas", cantidad: "porción normal", proteina: 7, carbohidratos: 65, grasas: 0 },
        ],
        nota: "Bebe todo el caldo. Es colágeno puro — minerales y proteína lenta de absorción.",
      },
      {
        id: "com-4",
        nombre: "Cualquier platillo — regla universal",
        tags: ["siempre aplica"],
        calorias: 750,
        proteina: 50,
        carbohidratos: 85,
        grasas: 15,
        ingredientes: [
          { nombre: "Proteína principal (lo que haya)", cantidad: "doble porción", proteina: 40, carbohidratos: 0, grasas: 12 },
          { nombre: "Tortilla de maíz (no harina)", cantidad: "3-4 piezas", proteina: 7, carbohidratos: 56, grasas: 4 },
          { nombre: "Aguacate (si hay)", cantidad: "½ pieza", proteina: 1, carbohidratos: 6, grasas: 11 },
          { nombre: "Toda la verdura disponible", cantidad: "todo", proteina: 2, carbohidratos: 10, grasas: 0 },
        ],
        nota: "NUNCA saltes esta comida. Es tu pre-entreno. Llegar al gym en ayunas a las 4pm destruye el rendimiento.",
      },
    ],
  },
  {
    id: "postEntreno",
    hora: "6:30 pm",
    nombre: "Post-entreno",
    opciones: [
      {
        id: "pe-1",
        nombre: "Picadillo warrior",
        tags: ["testosterona", "zinc", "principal"],
        calorias: 820,
        proteina: 58,
        carbohidratos: 56,
        grasas: 43,
        ingredientes: [
          { nombre: "Picadillo de res (220g)", cantidad: "220g", proteina: 38, carbohidratos: 12, grasas: 22 },
          { nombre: "2 huevos revueltos en mantequilla", cantidad: "2 piezas", proteina: 12, carbohidratos: 0, grasas: 10 },
          { nombre: "4 tortillas de maíz", cantidad: "4 piezas", proteina: 7, carbohidratos: 56, grasas: 4 },
          { nombre: "½ aguacate", cantidad: "½ pieza", proteina: 1, carbohidratos: 6, grasas: 11 },
        ],
      },
      {
        id: "pe-2",
        nombre: "Arrachera recovery",
        tags: ["testosterona", "premium"],
        calorias: 800,
        proteina: 62,
        carbohidratos: 65,
        grasas: 32,
        ingredientes: [
          { nombre: "Arrachera (200g)", cantidad: "200g", proteina: 44, carbohidratos: 0, grasas: 22 },
          { nombre: "2 huevos estrellados en mantequilla", cantidad: "2 piezas", proteina: 12, carbohidratos: 0, grasas: 10 },
          { nombre: "Arroz blanco (1 taza)", cantidad: "150g cocido", proteina: 4, carbohidratos: 45, grasas: 0 },
          { nombre: "Camote cocido (100g)", cantidad: "100g", proteina: 2, carbohidratos: 20, grasas: 0 },
        ],
      },
      {
        id: "pe-3",
        nombre: "Batido coco recovery",
        tags: ["rápido", "5 min", "raw"],
        calorias: 720,
        proteina: 30,
        carbohidratos: 95,
        grasas: 43,
        ingredientes: [
          { nombre: "3 huevos crudos", cantidad: "3 piezas", proteina: 18, carbohidratos: 0, grasas: 15 },
          { nombre: "Leche de coco de lata (300ml)", cantidad: "300ml", proteina: 2, carbohidratos: 6, grasas: 27 },
          { nombre: "Raw honey (2 cdas)", cantidad: "2 cdas", proteina: 0, carbohidratos: 34, grasas: 0 },
          { nombre: "2 plátanos", cantidad: "2 piezas", proteina: 2, carbohidratos: 54, grasas: 0 },
          { nombre: "Avena cruda (50g)", cantidad: "50g", proteina: 6, carbohidratos: 33, grasas: 3 },
        ],
        nota: "Para días sin tiempo de cocinar. El batido de leche de coco + raw honey + huevos es la recuperación más rápida del plan.",
      },
      {
        id: "pe-4",
        nombre: "Bistec tacos",
        tags: ["testosterona", "clásico"],
        calorias: 780,
        proteina: 52,
        carbohidratos: 62,
        grasas: 32,
        ingredientes: [
          { nombre: "Bistec de res (180g)", cantidad: "180g", proteina: 40, carbohidratos: 0, grasas: 20 },
          { nombre: "2 huevos fritos en mantequilla", cantidad: "2 piezas", proteina: 12, carbohidratos: 0, grasas: 10 },
          { nombre: "4 tortillas de maíz", cantidad: "4 piezas", proteina: 7, carbohidratos: 56, grasas: 4 },
          { nombre: "Limón + salsa natural", cantidad: "al gusto", proteina: 0, carbohidratos: 3, grasas: 0 },
        ],
      },
      {
        id: "pe-5",
        nombre: "Cecina recovery",
        tags: ["testosterona", "zinc"],
        calorias: 720,
        proteina: 55,
        carbohidratos: 50,
        grasas: 28,
        ingredientes: [
          { nombre: "Cecina (150g)", cantidad: "150g", proteina: 40, carbohidratos: 0, grasas: 15 },
          { nombre: "2 huevos en mantequilla", cantidad: "2 piezas", proteina: 12, carbohidratos: 0, grasas: 10 },
          { nombre: "3 tortillas de maíz", cantidad: "3 piezas", proteina: 5, carbohidratos: 42, grasas: 3 },
          { nombre: "Raw honey (1 cda)", cantidad: "1 cda", proteina: 0, carbohidratos: 17, grasas: 0 },
        ],
      },
    ],
  },
  {
    id: "cena",
    hora: "8:30 pm",
    nombre: "Cena",
    opciones: [
      {
        id: "cen-1",
        nombre: "Mexicano clásico",
        tags: ["familiar", "simple"],
        calorias: 520,
        proteina: 34,
        carbohidratos: 59,
        grasas: 40,
        ingredientes: [
          { nombre: "4 huevos a la mexicana (jitomate, cebolla, chile)", cantidad: "4 piezas", proteina: 24, carbohidratos: 8, grasas: 20 },
          { nombre: "3 tortillas de maíz", cantidad: "3 piezas", proteina: 5, carbohidratos: 42, grasas: 3 },
          { nombre: "Raw honey (1 cda)", cantidad: "1 cda", proteina: 0, carbohidratos: 17, grasas: 0 },
          { nombre: "Nueces naturales (30g)", cantidad: "30g", proteina: 5, carbohidratos: 4, grasas: 20 },
        ],
      },
      {
        id: "cen-2",
        nombre: "Machaca nocturna",
        tags: ["testosterona", "zinc"],
        calorias: 550,
        proteina: 44,
        carbohidratos: 42,
        grasas: 36,
        ingredientes: [
          { nombre: "Machaca con 3 huevos en mantequilla", cantidad: "80g + 3 huevos", proteina: 38, carbohidratos: 0, grasas: 25 },
          { nombre: "3 tortillas de maíz", cantidad: "3 piezas", proteina: 5, carbohidratos: 42, grasas: 3 },
          { nombre: "½ aguacate", cantidad: "½ pieza", proteina: 1, carbohidratos: 6, grasas: 11 },
        ],
      },
      {
        id: "cen-3",
        nombre: "Tacos de sardina",
        tags: ["omega-3", "acné", "ligero"],
        calorias: 480,
        proteina: 38,
        carbohidratos: 48,
        grasas: 18,
        ingredientes: [
          { nombre: "Sardinas en agua (2 latas)", cantidad: "170g", proteina: 30, carbohidratos: 0, grasas: 8 },
          { nombre: "3 tortillas de maíz", cantidad: "3 piezas", proteina: 5, carbohidratos: 42, grasas: 3 },
          { nombre: "½ aguacate", cantidad: "½ pieza", proteina: 1, carbohidratos: 6, grasas: 11 },
          { nombre: "Limón + cilantro + salsa", cantidad: "al gusto", proteina: 0, carbohidratos: 2, grasas: 0 },
        ],
      },
      {
        id: "cen-4",
        nombre: "Atún aguacate",
        tags: ["omega-3", "proteína alta"],
        calorias: 520,
        proteina: 50,
        carbohidratos: 24,
        grasas: 22,
        ingredientes: [
          { nombre: "Atún en agua (2 latas)", cantidad: "170g", proteina: 36, carbohidratos: 0, grasas: 2 },
          { nombre: "½ aguacate", cantidad: "½ pieza", proteina: 1, carbohidratos: 6, grasas: 11 },
          { nombre: "2 huevos cocidos", cantidad: "2 piezas", proteina: 12, carbohidratos: 0, grasas: 10 },
          { nombre: "1 fruta (naranja, manzana)", cantidad: "1 pieza", proteina: 0, carbohidratos: 20, grasas: 0 },
        ],
      },
    ],
  },
];

export const SLOT_LABELS: Record<string, string> = {
  desayuno: "Desayuno",
  mediaManana: "Media mañana",
  comida: "Comida",
  postEntreno: "Post-entreno",
  cena: "Cena",
};
